### ISSUE TITLE
Configuration for entity events should move.

### ISSUE THREAD

**Issue by dionsnoeijen** [dionsnoeijen/sexy-field#17]
Right now we have:

``` yml
field:
  name: Updated
  handle: updated
  type: DateTimeField
  entityEvents:
    - prePersist
    - preUpdate
  form:
    all:
      label: Update date
```

This should be:

``` yml
field:
  name: Updated
  handle: updated
  type: DateTimeField
  generator:
    entity:
      event:
        - prePersist
        - preUpdate
  form:
    all:
      label: Update date
```
Since all config that targets a specific package dependency are in their own config block.
